# Generated by Django 4.0.4 on 2022-11-27 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTeLlevoAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.IntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('fech_mensaje', models.DateField(verbose_name=models.DateField(auto_now_add=True))),
                ('id_enviador', models.IntegerField()),
                ('id_receptor', models.IntegerField()),
            ],
            options={
                'db_table': 'db_mensaje',
            },
        ),
        migrations.RemoveField(
            model_name='pasajero',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='id_pasajero',
        ),
        migrations.AlterField(
            model_name='pago',
            name='fech_pago',
            field=models.DateField(verbose_name=models.DateField(auto_now_add=True)),
        ),
        migrations.CreateModel(
            name='Lobby_Viaje',
            fields=[
                ('id_lobby_viaje', models.IntegerField(primary_key=True, serialize=False)),
                ('id_pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTeLlevoAPP.pasajero')),
                ('id_viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApiTeLlevoAPP.viaje')),
            ],
            options={
                'db_table': 'db_lobby_viaje',
            },
        ),
    ]
