# Generated by Django 4.0.4 on 2022-11-27 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTeLlevoAPP', '0002_mensaje_remove_pasajero_password2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasajero',
            name='imagen_pasajero',
        ),
    ]
