# Generated by Django 4.0.4 on 2022-11-27 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiTeLlevoAPP', '0003_remove_pasajero_imagen_pasajero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='imagen_vehiculo',
        ),
    ]
